accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('logout/', views.logout, name='logout'),
    path('update_profile/', views.update_profile, name="update_profile")
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import redirect
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newlsetter')),
    path('loyalty/', include('loyalty.urls', namespace='loyalty')),
    path('tombola/', include('tombola.urls', namespace='tombola')),
    
    #apis
    path('v1/api/', include('apis.urls', namespace='apis')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),



    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('list_product/', views.list_product, name='list_product'),
    path('product/<variation_id>/', views.product_detail, name='product_detail'),
    path('category/<category_slug>/', views.product_by_category, name='product_by_category'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
import pycountry   # type: ignore

class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, country, password=None):
        if not email:
            raise ValueError("User must have an email adress.")
        if not username:
            raise ValueError("User must have an username.")
        
        user = self.model(
            email      = self.normalize_email(email),
            username   = username,
            first_name = first_name,
            last_name  = last_name,
            country    = country,
        )
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, first_name, last_name, username, email, password, country='US'):
        user = self.create_user(
            first_name = first_name,
            last_name  = last_name,
            username   = username,
            email      = self.normalize_email(email),
            country    = country,
            password   = password
        )
        user.is_staff      = True
        user.is_superadmin = True  
        user.is_admin      = True     
        user.is_active     = True

        user.save(using=self._db)

        return user


class Account(AbstractBaseUser):
    @staticmethod
    def get_country():
        countries       = list(pycountry.countries)
        country_choices = [(country.alpha_2, country.name) for country in countries]
        return country_choices

    first_name   = models.CharField(max_length=250)
    last_name    = models.CharField(max_length=250)
    email        = models.EmailField(max_length=100, unique=True)
    username     = models.CharField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=50)
    country      = models.CharField(max_length=2, choices=get_country(), default='US')

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)

    is_active     = models.BooleanField(default=False)
    is_staff      = models.BooleanField(default=False)
    is_admin      = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD  = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'username']

    objects = MyAccountManager()

    def __str__(self):
        return self.email
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
    
    def has_module_perms(self, app_label):
        return True
    
    def get_full_name(self):
        return self.first_name +' '+ self.last_name   

accounts/forms.py
from django import forms
from .models import Account

class RegisterForm(forms.ModelForm):

    password           = forms.CharField(widget=forms.PasswordInput)    
    confirmed_password = forms.CharField(widget=forms.PasswordInput)    
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'country']
    
    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password           = cleaned_data.get('password')
        confirmed_password = cleaned_data.get('confirmed_password')
        
        if password and confirmed_password and password != confirmed_password:
            raise forms.ValidationError("Your password didn't match.")
        return cleaned_data


    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter your first name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter your last name'
        self.fields['email'].widget.attrs['placeholder'] = 'Your email adress'
        self.fields['phone_number'].widget.attrs['placeholder'] = 'Your phone number'
        self.fields['password'].widget.attrs['placeholder'] = 'Enter your password'
        self.fields['confirmed_password'].widget.attrs['placeholder'] = 'Confirm your password'




class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'username', 'phone_number', 'country', 'email']
        widgets = {
            'country': forms.Select(choices=Account.get_country())
        }
 

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import RegisterForm, UserUpdateForm
from .models import Account
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

# ACTIVATION ACCOUNT
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.http import HttpResponse
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name   = form.cleaned_data['first_name']
            last_name    = form.cleaned_data['last_name']
            email        = form.cleaned_data['email']
            country      = form.cleaned_data['country']
            password     = form.cleaned_data['password']
            username     = email.split('@')[0]
            phone_number = form.cleaned_data['phone_number']

            user = Account.objects.create_user(
                first_name = first_name,
                last_name  = last_name,
                email      = email,
                username   = username,
                country    =country,
                password   =password
            )
            user.phone_number = phone_number
            user.save()
            #User Activate
            domain_name   = get_current_site(request)
            email_subject = 'Please Activate Your Account'
            message       = render_to_string('accounts/account_verification_email.html', {
                'user':user,
                'domain':domain_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token':default_token_generator.make_token(user),
            })
            to_email  = email
            send_mail = EmailMessage(email_subject, message, to=[to_email])
            send_mail.send()
            login_url = reverse('accounts:login')  # Resolves to /account/login/
            redirect_url = f"{login_url}?command=verification&mail={email}"
            return HttpResponseRedirect(redirect_url)
    else:
        form = RegisterForm()
    
    context = {
        'form':form
    }
    return render(request, 'accounts/register.html', context)


def login(request):
    if request.method == 'POST':
        email    = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(email=email, password=password)
        if user is not None:
            auth_login(request, user)
            messages.success(request, 'Login is successfully')
            return redirect('store:home')
        else:
            messages.error(request, 'Invalid Login')
            return redirect('accounts:login')
    
    return render(request, 'accounts/login.html')


def activate(request, uidb64, token):
    try:
        uid  = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None
    
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Your account is activated')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Your Account is not active, Please again.')
        return redirect('accounts:register')



def logout(request):
    auth_logout(request)
    return redirect('accounts:login')




@login_required
def update_profile(request):
    user = request.user
    print("User instance type:", type(user))
    print(user)
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            print("✅ Updated account:", Account.__dict__)
            user.save(force_update=True)
            messages.success(request, "Votre profil a été mis à jour avec succès.")
            return redirect('accounts:update_profile') 
        else:
            print("❌ Form errors:", form.errors)
    else:
        form = UserUpdateForm(instance=user)
    
    return render(request, 'accounts/update_profile.html', {'form': form})
 

templates/accounts/account_verification_email.html
{% autoescape off %}

Hii {{user.first_name}},

Please Click on the blue link to confirm your registration.

http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

if you think it's not you, Please ignore this email.



{% endautoescape %}
 

templates/accounts/login.html
{%extends 'base.html'%}
{%load static%}
{%block title%}Login{%endblock%}

{%block content%}
{% if request.GET.command == 'verification' %}
<div class="alert">
    <div class="alert_access">
        <h4 class="alert_heading">Well Done.</h4>
        <p>Thanks you for registration with us, have send you a verification email to you.</p>
        <p>If already verified <a href="{%url 'accounts:login'%}"> Sign in</a></p>
    </div>
</div>
{%else%}
<div class="register">
    <div class="form_left">
        <p style="z-index: 999;">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>    
            <a href="{%url 'store:home' %}">Back to Home</a>
        </p>
        <div class="background">
            <img style="transform: translate(0px, -50px); " src="{% static 'images/store-card-1-bg.png' %}" alt="register">
        </div>
    </div>
    <div class="form_right" style="transform: translateY(40px);">
        <h1>Login</h1>
        {%include 'includes/alerts.html'%}
        <form method="post" action="{%url 'accounts:login'%}">
            {% csrf_token %}
            <div class="form_group">
                <label for="email">Email:</label>
                <input name="email" type="email" id="email" placeholder="Your email">
            </div>
            <div class="form_group">
                <label for="password">password:</label>
                <div class="input_password">
                    <input name="password" type="password" id="password" placeholder="Your first name">
                    <i class="uil uil-eye"></i>
                </div>
            </div>
            <!-- non-field errors -->
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="errors"> * {{ error }}</p>
                {% endfor %}
            {% endif %}
            <input type="submit" value="Create Account" class="btn_submit">
        </form>
        <p>You don't have an account? <a href="{%url 'accounts:register'%}">Sign Up</a></p>
    </div>
</div>
{%endif%}

{%endblock%}

templates/accounts/register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
<!--Register Form-->
<div class="register">
    <div class="form_left">
        <p>
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>    
            <a href="{%url 'store:home' %}">Back to Home</a>
        </p>
        <div class="background">
            <img src="{% static 'images/store-card-1-bg.png' %}" alt="register">
        </div>
    </div>
    
    <div class="form_right">
        <h1>Create Account</h1>
        <p>Join Senuoy store for exclusive deals and offers</p>

        <form method="post">
            {% csrf_token %}
            <div class="form_names">
                <div class="form_group">
                    <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}:</label>
                    {{form.first_name}}
                    {% if form.first_name.errors %}
                        {% for error in form.first_name.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form_group">
                    <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}:</label>
                    {{form.last_name}}
                    {% if form.last_name.errors %}
                        {% for error in form.last_name.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="form_names">
                <div class="form_group">
                    <label for="{{ form.country.id_for_label }}">{{ form.country.label }}:</label>
                    {{form.country}}
                    {% if form.country.errors %}
                        {% for error in form.country.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="form_group">
                    <label for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}:</label>
                    {{form.phone_number}}
                    {% if form.phone_number.errors %}
                        {% for error in form.phone_number.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="form_group">
                    <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
                    {{form.email}}
                    {% if form.email.errors %}
                        {% for error in form.email.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
            </div>

            <div class="form_group">
                    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}:</label>
                    {{form.password}}
                    {% if form.password.errors %}
                        {% for error in form.password.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
            </div>
            <div class="form_group">
                    <label for="{{ form.confirmed_password.id_for_label }}">{{ form.confirmed_password.label }}:</label>
                    {{form.confirmed_password}}
                    {% if form.confirmed_password.errors %}
                        {% for error in form.confirmed_password.errors %}
                            <p class="errors">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
            </div>

            <!-- non-field errors -->
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class="errors"> * {{ error }}</p>
                {% endfor %}
            {% endif %}

            <input type="submit" value="Create Account" class="btn_submit">
        </form>

        <p>Already have an account? <a href="{%url 'accounts:login'%}">Sign in</a></p>
    </div>
</div>
<!--Register Form-->
{% endblock %}

templates/accounts/update_profile.html
{%extends 'base.html'%}
{%block title%}Update Account{%endblock%}
{%block content%}
<style>
    .update_account{
        max-width: 1200px;
        padding: 40px;
        width: 90%;
        margin: 130px auto;
        gap: 20px;
        background-color: white;
        border-radius: 20px;
        box-shadow: rgba(17, 12, 46, 0.15) 0px 48px 100px 0px; 
    }
    .update_account h1{
        color: #111827;
        font-weight: bold;
        text-align: center;
        font-size: 19px;
        text-transform: uppercase;
        letter-spacing: 1px; 
        margin-bottom: 20px;
    }
    .update_account p.errors{
        text-align: left;
        color: rgb(187, 32, 32);
        margin: 0;
        padding-left: 10px;
        font-size: 12px;
    }
    .update_account form .form_names{
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        column-gap: 16px;
    }
    form .form_group{
        display: flex;
        flex-direction: column;
        gap: 4px;
        margin-bottom: 24px;
    }
    .form_group label{
        color: #374151;
        font-size: 14px;
        line-height: 20px;
        text-transform: capitalize;
        letter-spacing: 1px;
        font-weight: 500;
        margin-bottom: 5px; 
    }
    .form_group .input_password{
        position: relative;
    }
    .form_group .input_password input{
        width: 100%;
    } 
    .form_group .input_password i{
        color: #82868b;
        font-size: 20px;
        cursor: pointer;
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%); 
    }
    .form_group input{
        padding: 9px;
        border-radius: 5px;
        outline: none;
        border: 1px solid #D1D5DB;
        height: 42px;
    }
    form button{
        width: 100%;
        padding: 15px 0; 
        background-color: #9333EA;
        color: #fff;
        border-radius: 10px;
        border: 1px solid #9333EA;
        cursor: pointer;
        margin-bottom: 13px;
        letter-spacing: 1px;
        text-transform: capitalize; 
        transition: all .3s ease;
    }
    form button:hover{
        background-color: #fff;
        color: #9333EA;
        border: 1px solid #9333EA;
    }
    form button.disabled, form button.disabled:hover{
        background-color: #9233ea81;
        border: 1px solid #9233ea81;
        color: #fff;
        cursor: auto;
    }
    #id_country,
    #id_country::picker(select){
        appearance: base-select;
    }
    #id_country{
        padding: 9px;
        border-radius: 5px;
        outline: none;
        border: 1px solid #D1D5DB;
        height: 42px;
    }
    #id_country::picker(select){
        width: 50%;
        border: 1px solid #D1D5DB;
    }
</style>

<div class="update_account">
    <h1>Update Account</h1>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" style="margin: 20px auto; color:rgb(0, 0, 0); font-size:19px;">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <form method="post" action="" id="profile-form">
        {% csrf_token %}
        <div class="form_names">
            <div class="form_group">
                <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}:</label>
                {{form.first_name}}
                {% if form.first_name.errors %}
                    {% for error in form.first_name.errors %}
                        <p class="errors">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form_group">
                <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}:</label>
                {{form.last_name}}
                {% if form.last_name.errors %}
                    {% for error in form.last_name.errors %}
                        <p class="errors">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form_names">
            <div class="form_group">
                <label for="{{ form.country.id_for_label }}">{{ form.country.label }}:</label>
                {{form.country}}
                {% if form.country.errors %}
                    {% for error in form.country.errors %}
                        <p class="errors">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form_group">
                <label for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}:</label>
                {{form.phone_number}}
                {% if form.phone_number.errors %}
                    {% for error in form.phone_number.errors %}
                        <p class="errors">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="form_names">
            <div class="form_group">
                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
                {{form.email}}
                {% if form.email.errors %}
                    {% for error in form.email.errors %}
                        <p class="errors">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="form_group">
                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}:</label>
                {{form.username}}
                {% if form.username.errors %}
                    {% for error in form.username.errors %}
                        <p class="errors">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <!-- non-field errors -->
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="errors"> * {{ error }}</p>
            {% endfor %}
        {% endif %}

        <button type="submit" id="submit-btn" >Update Account</button>
    </form>
</div>

<script>
    setTimeout(function() {
        const alert = document.querySelector('.alert');
        if (alert) {
        alert.style.transition = 'opacity 0.5s ease-out';
        alert.style.opacity = '0';
        setTimeout(() => alert.remove(), 700000);
        }
    }, 3000); // disparaît après 3 secondes


    document.addEventListener('DOMContentLoaded', function () {
        const form = document.getElementById('profile-form');
        const submitBtn = document.getElementById('submit-btn');

        // Capture initial values of all inputs
        const initialData = {};
        [...form.elements].forEach(el => {
            if (el.name && (el.type !== 'submit' && el.type !== 'button')) {
                initialData[el.name] = el.value;
            }
        });

        // Check on input/change
        form.addEventListener('input',checkInput);
        function checkInput (){
            let changed = false;
            [...form.elements].forEach(el => {
                if (el.name && (el.type !== 'submit' && el.type !== 'button')) {
                    if (el.value !== initialData[el.name]) {
                        changed = true;
                    }
                }
            });

            // Enable/disable submit button + toggle .disabled class
            if (changed) {
                submitBtn.classList.remove('disabled');
            } else {
                submitBtn.classList.add('disabled');
            }
            submitBtn.disabled = !changed
        }
        checkInput()
    });

</script>

{%endblock%}