apis/urls.py
from django.urls import path
from . import views

app_name = 'apis'

urlpatterns = [
    path('category/', views.category_api, name='category_api'),
    path('category/<slug>/', views.category_api, name='by_category_api'),

    path('product/', views.product_api, name='product_api'),
    path('variation/', views.variation_api, name='variation_api'),
    
    path('color/', views.color_api, name='color_api'),
    path('color/<slug>/', views.color_api, name='by_color_api'),

    path('register/', views.Registrationuser_api, name='register_api'),
    path('activate/<uidb64>/<token>/', views.Activate_api, name="activation_email_api"),

    path('logout/', views.logout, name='logout'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:variation_id>/', views.add_to_cart, name='add_to_cart'),
    path('add_from_form/<int:variation_id>/', views.add_from_form, name='add_from_form'),
    path('remove/<int:variation_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('', views.cart_detail, name='cart_detail'),
]

orders/urls.py
from . import views
from django.urls import path

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_payment/<order_id>/', views.order_payment, name='order_payment'),
    path('admin/pdf/<int:order_id>/', views.admin_order_pdf, name='admin_order_pdf'),

    #stripe
    path('create_stripe_session/<order_id>/', views.create_stripe_session, name="create_stripe_session"),
    path('payment_success/', views.payment_success, name="payment_stripe_success"),
    path('payment_failed/' , views.payment_failed , name="payment_stripe_failed"),
    path('stripe/webhook/' , views.stripe_webhook , name="stripe_webhook"),

    path('history/', views.orders_history, name='orders_history'),
    path('history/order/<order_id>/', views.order_detail, name="order_detail"),

]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import redirect
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newlsetter')),
    path('loyalty/', include('loyalty.urls', namespace='loyalty')),
    path('tombola/', include('tombola.urls', namespace='tombola')),
    
    #apis
    path('v1/api/', include('apis.urls', namespace='apis')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),



    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('list_product/', views.list_product, name='list_product'),
    path('product/<variation_id>/', views.product_detail, name='product_detail'),
    path('category/<category_slug>/', views.product_by_category, name='product_by_category'),
]

templates/includes/alerts.html
<style>
    .message-container{
        width: 90%;
        max-width: 500px;
        margin: 20px auto;
    }
    [class^="alert-"]{
        padding: 20px;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: 20px;
        box-shadow: white 0px 48px 100px 0px;
        color: white;
    }
    .alert-success{
        background-color: rgb(16, 185, 129);
    }
    .alert-danger{
        background-color:  rgb(239, 68, 68);
    }
    .message-container h5{
        text-align: center;
        margin-bottom: 0;
        color: white;
    }
</style>

<div class="message-container">
    {% if messages %}
        {% for message in messages %}
            <div id="message" class="x">
                <div {% if message.tags %}class="alert-{{ message.tags }}"{% endif %} role="alert">
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                     <h5> {{ message }}</h5>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function(){
        setTimeout(function(){
            $('.x').fadeOut('slow');
        }, 3000);
    });
</script>  

templates/includes/footer.html
{% load static i18n %}
<!--Footer-->
<footer>
    <div class="content">
        <div class="wrapper">
            <div class="col">
                <h1>{% trans "Aide" %} <img src="{% static 'images/To bottom.png' %}" alt=""></h1>
                <div class="dropdown">
                    <a href="#">{% trans "Questions frequentes" %}</a>
                    <a href="#">{% trans "Faire un retour" %}</a>
                </div>
            </div>
            <div class="col">
                <h1>{% trans "Company" %} <img src="{% static 'images/To bottom.png' %}" alt=""></h1>
                <div class="dropdown">
                    <a href="#">{% trans "Nous" %}</a>
                    <a href="#">{% trans "Participer avec nous" %}</a>
                </div>
            </div>
        </div>
        <div class="wrapper_list">
            <div class="col">
                <h1>{% trans "Our App" %} <img src="{% static 'images/To bottom.png' %}" alt=""></h1>
                <div class="dropdown">
                    <div class="imgs">
                        <img class="apps" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/footer/downloadApp/ios.png" alt="">
                        <img class="apps" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/footer/downloadApp/android.png" alt="">
                    </div>
                </div>
            </div>
            <div class="col">
                <h1>{% trans "Payment" %} <img src="{% static 'images/To bottom.png' %}" alt=""></h1>
                <div class="dropdown">
                    <div class="imgs">
                        <img class="card" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/payment/VISA.svg" alt="">
                        <img class="card" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/payment/MasterCard.svg" alt="">
                    </div>
                </div>
            </div>
        </div>
        <div class="newsletter">
            <div class="col">
                <h1>{% trans "Newsletter" %}<img src="{%static 'images/To bottom.png'%}" alt=""></h1>
                <div class="dropdown">
                    <form method="post" action="{% url 'newsletter:subscribe_newsletter' %}">
                        {% csrf_token %}
                        {{ subscriber_form.email }}
                        <button type="submit">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="message"><path fill="#FFFFFF" d="M20.34,9.32l-14-7a3,3,0,0,0-4.08,3.9l2.4,5.37h0a1.06,1.06,0,0,1,0,.82l-2.4,5.37A3,3,0,0,0,5,22a3.14,3.14,0,0,0,1.35-.32l14-7a3,3,0,0,0,0-5.36Zm-.89,3.57-14,7a1,1,0,0,1-1.35-1.3l2.39-5.37A2,2,0,0,0,6.57,13h6.89a1,1,0,0,0,0-2H6.57a2,2,0,0,0-.08-.22L4.1,5.41a1,1,0,0,1,1.35-1.3l14,7a1,1,0,0,1,0,1.78Z"></path></svg>
                        </button>
                    </form>
                    <!-- non-field errors -->
                    {% if subscriber_form.non_field_errors %}
                        {% for error in subscriber_form.non_field_errors %}
                            <p class="errors"> * {{ error }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="col">
                <h1>{% trans "Suivez-nous !" %}<img src="{%static 'images/To bottom.png'%}" alt=""></h1>
                <div class="dropdown">
                    <div class="imgs">
                        <img class="social" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/footer/social/21/tiktok.png" alt="">
                        <img class="social" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/footer/social/21/instagram.png" alt="">
                        <img class="social" src="https://static.pullandbear.net/2/static2/itxwebstandard/images/footer/social/21/facebook.png" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content_bottom">
        <ul>
            <li>{% trans "Cookie Preferences" %}</li>
            <li>{% trans "Privacy Policy" %}</li>
            <li>{% trans "Purchase Conditions" %}</li>
            <li>{% trans "Cookie Policy" %}</li>
            <li>{% trans "T&C Senuoy Community" %}</li>
        </ul>
    </div>
</footer>

<script src="{% static 'js/footer.js' %}"></script>

templates/includes/header.html
{%load static%}
<style>
    .account a {
        position: relative;
    }
    .account a span{
        position: absolute;
        top: 0;
        right: 13px;
        padding: 5px;
        width: 20px;
        height: 20px;
        border-radius: 50%;
        background-color: red;
        color: white;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 14px;
        font-weight: bold;
    }
    form.language{
        display: flex;
        gap: 5px;
        align-items: center;
        width: max-content;
        margin-left: 20px;
    }
    form.language button{
        height: 30px;
        width: 40px;
        padding: 0;
        margin: 0 10px;
        background-color: transparent;
        cursor: pointer;
        border: none;
        outline: none;
        border-radius: 5px;
    }
    form.language button.active{
        border: 2px solid rgb(0, 0, 0);
        padding: 1px;
    }
    form.language button img{
        width: 100%;
        height: 100%;
        border-radius: 5px;
    }        
</style>
<div class="container">
    <header>
        <div class="logo"><a href="{%url 'store:home'%}">Senuoy</a></div>
        <div class="nav">
            <!--
            <div class="search">
                <input type="text" placeholder="Search...">
                <i class="uil uil-search"></i>
            </div> 
            <nav>
                <a href="">Home</a>
                <a href="">Home</a>
                <a href="">Home</a>
            </nav>
            --> 
            <div class="menuhover">
                <a class="menu" href="javascript:void(0)">
                    <i class="uil uil-bars"></i>
                    <span>Menu</span>
                </a> 
            </div>
            <div class="account">
                {%if not request.user.is_authenticated%}
                <a href="{%url 'accounts:register'%}"><i class="uil uil-user"></i></a>
                {%endif%}
                <a href="{%url 'cart:cart_detail'%}">
                    <i class="uil uil-shopping-bag"></i>
                    {% if cart|length < 100 and cart|length > 0 %}
                        <span>
                            {{ cart|length }}
                        </span>
                    {%elif cart|length > 100 %}
                        <span>
                            +99
                        </span>
                    {%else%}
                    <!--Show nothing-->
                    {%endif%}
                </a>
                <a href="#"><i class="uil uil-heart"></i></a>
                <!--
                <form action="{% url 'set_language' %}" method="post" class="language">
                    {% csrf_token %}
                    <button type="submit" name="language" value="fr" class="{% if LANGUAGE_CODE == 'fr' %}active{% endif %}">
                        <img src="https://flagcdn.com/fr.svg" alt="Saudi Arabia">
                    </button>
                    <button type="submit" name="language" value="ar" class="{% if LANGUAGE_CODE == 'ar' %}active{% endif %}">
                        <img src="https://flagcdn.com/sa.svg" alt="Saudi Arabia">
                    </button>
                </form>
                -->
            </div>            
        </div>
    </header>
    <div class="overly"></div>
    <main class="main_layout">
            <!--SIDE BAR-->
            
            <aside class="sidebar">
                <div class="link_container">
                    <div class="menuhover nav_left"> 
                        <a class="menu" href="javascript:void(0)">
                            <i class="uil uil-bars"></i>
                            <span>Menu</span>
                        </a>
                        {%if request.user.is_authenticated%}
                        <div class="user_info">
                            <p class="store" style="color: rgb(102, 102, 102);">Welcome <span style="color: black;">{{request.user.first_name}}</span> !</p>
                        </div>
                        {%endif%}
                    </div>
                    <div class="link_section">
                        <a href="{%url 'store:home'%}" class="link_item">
                            <i class="uil uil-estate"></i>Home
                        </a>
                    </div>
                    <div class="link_section drop"> 
                        <div href="#" class="link_item dropdown">
                            <i class="uil uil-database-alt"></i>
                            <p style="margin-bottom:0; font-size:14px;">Categories</p>
                            <i class="uil uil-arrow-down up_down active"></i>
                            <i class="uil uil-arrow-up up_down"></i>
                        </div>
                        <div class="dropcontent">
                            {% for category in all_categories %}
                            <a href="{%url 'store:product_by_category' category.slug %}" class="link_item">
                                <img src="{{category.image.url}}" alt="">
                                <p style="margin-bottom: 0; font-size:14px;">{{category.slug}}</p>
                            </a>
                            {%endfor%}
                        </div>
                    </div>
                    
                    <div class="section_separator"></div>

                    <div class="link_section">
                        <h4 class="section_title">Your</h4>
                        <a href="{%url 'accounts:update_profile' %}" class="link_item">
                            <i class="uil uil-user-square"></i>Mon compte
                        </a>
                        <a href="{%url 'orders:orders_history'%}" class="link_item">
                            <i class="uil uil-history"></i>Mes Achats
                        </a>
                    </div>
                    <div class="section_separator"></div>

                    <div class="link_section">
                        <h4 class="section_title">Explore</h4>
                        <a href="{%url 'tombola:home'%}" class="link_item">
                            <i class="uil uil-gift"></i>Tombola
                        </a>
                        <a href="{%url 'loyalty:home_loyalty'%}" class="link_item">
                            <i class="uil uil-archive-alt"></i>Systeme de fidélité
                        </a>
                    </div>
                    <div class="section_separator"></div>
                    
                    <div class="link_section drop"> 
                        <div href="#" class="link_item dropdown">
                            <i class="uil uil-database-alt"></i>
                            <p style="margin-bottom:0; font-size:14px;">languages</p>
                            <i class="uil uil-arrow-down up_down active"></i>
                            <i class="uil uil-arrow-up up_down"></i>
                        </div>
                        <div class="dropcontent">
                            <form action="{% url 'set_language' %}" method="post" class="language">
                                {% csrf_token %}
                                <button type="submit" name="language" value="fr" class="{% if LANGUAGE_CODE == 'fr' %}active{% endif %}">
                                    <img src="https://flagcdn.com/fr.svg" alt="Saudi Arabia">
                                </button>
                                <button type="submit" name="language" value="ar" class="{% if LANGUAGE_CODE == 'ar' %}active{% endif %}">
                                    <img src="https://flagcdn.com/sa.svg" alt="Saudi Arabia">
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="link_section">
                        <a href="#" class="link_item">
                            <i class="uil uil-setting"></i>Settings
                        </a>
                        <a href="#" class="link_item">
                            <i class="uil uil-info"></i>Report
                        </a>
                        <a href="#" class="link_item">
                            <i class="uil uil-question-circle"></i>Help
                        </a>
                        <a href="#" class="link_item">
                            <i class="uil uil-exclamation-triangle"></i>FeedBack
                        </a>
                    </div>
                    {%if request.user.is_authenticated %}
                    <div class="menu_logout">
                        <a href="{%url 'accounts:logout'%}" class="logout_link">
                            <i class="uil uil-signout"></i>
                            <p style="font-size: 14px; color:white; margin-bottom:0;">Logout</p>
                        </a>
                    </div>
                    {%else%}
                    <div class="menu_sign_up_in">
                        <a href="{%url 'accounts:login'%}" class="singin_link">
                            <i class="uil uil-signout"></i>
                            <p style="color: white; font-size:16px; margin-bottom:0;">Sign in</p>
                        </a>
                        <a href="{%url 'accounts:register'%}" class="signup_link">
                            <i class="uil uil-signout"></i>
                            <p style="color: white; font-size:16px; margin-bottom:0;">Register</p>
                        </a>
                    </div>
                    {%endif%}
                    

                </div>
            </aside>
    </main>
</div>

<script>
    const link_sections_drop = document.querySelectorAll(".link_section.drop");
    const up_downs = document.querySelectorAll(".sidebar .link_section .link_item .up_down");

    link_sections_drop.forEach(link_section_drop => {
        link_section_drop.addEventListener('click', () => {
            link_section_drop.classList.toggle('active');

            const upDownsInSection = link_section_drop.querySelectorAll(".link_item .up_down");
            upDownsInSection.forEach(btn => {
                btn.classList.toggle('active');
            });
        });
    });



    const menuBtn = document.querySelectorAll(".menuhover")
    const overly = document.querySelector(".overly")
    menuBtn.forEach(btn =>{
        btn.addEventListener("click", ()=>{
            document.body.classList.toggle("sidebar_hidden")
        })
    })
    overly.addEventListener("click", ()=>{
        document.body.classList.toggle("sidebar_hidden")
    })

</script>