cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:variation_id>/', views.add_to_cart, name='add_to_cart'),
    path('add_from_form/<int:variation_id>/', views.add_from_form, name='add_from_form'),
    path('remove/<int:variation_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('', views.cart_detail, name='cart_detail'),
]

orders/urls.py
from . import views
from django.urls import path

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('order_payment/<order_id>/', views.order_payment, name='order_payment'),
    path('admin/pdf/<int:order_id>/', views.admin_order_pdf, name='admin_order_pdf'),

    #stripe
    path('create_stripe_session/<order_id>/', views.create_stripe_session, name="create_stripe_session"),
    path('payment_success/', views.payment_success, name="payment_stripe_success"),
    path('payment_failed/' , views.payment_failed , name="payment_stripe_failed"),
    path('stripe/webhook/' , views.stripe_webhook , name="stripe_webhook"),

    path('history/', views.orders_history, name='orders_history'),
    path('history/order/<order_id>/', views.order_detail, name="order_detail"),

]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import redirect
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newlsetter')),
    path('loyalty/', include('loyalty.urls', namespace='loyalty')),
    path('tombola/', include('tombola.urls', namespace='tombola')),
    
    #apis
    path('v1/api/', include('apis.urls', namespace='apis')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),



    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('list_product/', views.list_product, name='list_product'),
    path('product/<variation_id>/', views.product_detail, name='product_detail'),
    path('category/<category_slug>/', views.product_by_category, name='product_by_category'),
]

orders/models.py
from django.db import models
import random
import string
from django.utils import timezone
from store.models import Variation
from accounts.models import Account

def generate_order_id(length=8):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choices(characters, k=length))

class Order(models.Model):
    order_id     = models.CharField(max_length=8, default=generate_order_id, unique=True)
    first_name   = models.CharField(max_length=50)
    last_name    = models.CharField(max_length=50)
    email        = models.EmailField()
    address      = models.CharField(max_length=200)
    postal_code  = models.PositiveIntegerField()
    city         = models.CharField(max_length=100)
    created_at   = models.DateTimeField(default=timezone.now)
    update_at    = models.DateTimeField(auto_now=True)
    paid         = models.BooleanField(default=False)
    points_added = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at'] 
        indexes  = [
            models.Index(fields=['-created_at'])
        ]

    def __str__(self):
        return f'Order ID: {self.order_id}'

    def get_full_name(self):
        return self.first_name +' '+ self.last_name    
    
    def save(self, *args, **kwargs):
        if not self.order_id:
            unique_id = generate_order_id()
            while Order.objects.filter(order_id=unique_id).exists():
                unique_id = generate_order_id()
            self.order_id = unique_id
        super().save(*args,**kwargs)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    def get_quantity(self):
        return sum(item.quantity for item in self.items.all())
    
class OrderItem(models.Model):
    order          = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product        = models.ForeignKey(Variation, related_name='order_item', on_delete=models.CASCADE)
    original_price = models.DecimalField(max_digits=6, decimal_places=2)
    sale_price     = models.DecimalField(max_digits=6, decimal_places=2)
    quantity       = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'{self.id}'
    
    def get_cost(self):
        return self.sale_price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from django.core.exceptions import ValidationError

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']


    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs['placeholder']  = 'Enter your first name'
        self.fields['last_name'].widget.attrs['placeholder']   = 'Enter your last name'
        self.fields['email'].widget.attrs['placeholder']       = 'Your email adress'
        self.fields['address'].widget.attrs['placeholder']      = 'Address of your residence'
        self.fields['postal_code'].widget.attrs['placeholder'] = 'Postal Code'
        self.fields['city'].widget.attrs['placeholder']        = 'City'
              

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import OrderItem, Order
from coupons.models import Coupon
from .forms import OrderCreateForm
from cart.cart import Cart
from django.conf import settings
from .tasks import send_emails, payement_completed
from django.views.decorators.csrf import csrf_exempt
import stripe


from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from django.contrib.admin.views.decorators import staff_member_required
import weasyprint # type: ignore
import os
import json

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/pdf.html', {'order':order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.order_id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response)
    return response


def order_create(request):
    cart = Cart(request) 
    success = False
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order          = order,
                    product        = item['variation'],
                    original_price = item['original_price'],
                    sale_price     = item['final_price'],  # <-- This is now coupon-aware
                    quantity       = item['quantity'],
                ) 
            success = True 
            cart.clear() 

            send_emails.delay(order.id, form.cleaned_data['email']) #task celery
            #return redirect('orders:pay_order', order_id=order.id)
            # 🔁 Redirect to Stripe checkout
            #return redirect('orders:create_stripe_session', order_id=order.order_id)
            return redirect('orders:order_payment', order_id=order.order_id)

        return render(request, 'orders/created.html', {'order':order, 'success':success})
    else:
        form = OrderCreateForm()
    
    return render(request, 'orders/created.html', {'form':form, 'cart':cart})
    

# payment page view (GET)
def order_payment(request, order_id):
    order = get_object_or_404(Order, order_id=order_id)
    return render(request, 'orders/payment.html', {'order': order})

stripe.api_key = settings.STRIPE_SECRET_KEY

def create_stripe_session(request, order_id):
    order = get_object_or_404(Order, order_id=order_id)
    cart = Cart(request)

    coupon_id = str(cart.coupon.id) if cart.coupon else ""

    line_items = []
    for item in order.items.all():
        line_items.append({
            'price_data': {
                'currency': 'usd',
                'product_data': {
                    'name': item.product.product.name,
                },
                'unit_amount': int(item.sale_price * 100),
            },
            'quantity': item.quantity,
        })

    try:
        session = stripe.checkout.Session.create(
            payment_method_types = ["card"],
            customer_email       = request.user.email if request.user.is_authenticated else order.email,
            line_items=line_items,
            mode="payment",
            success_url = f"http://localhost:8000/fr/orders/payment_success?session_id={{CHECKOUT_SESSION_ID}}&order_id={order.order_id}",
            cancel_url  = "http://localhost:8000/fr/orders/payment_failed",
            metadata={
                'order_id': order.order_id,
                'coupon_id': coupon_id,
            },
        )
        return JsonResponse({"checkout_url":session.url})
    
    except stripe.error.StripeError as e:
        return JsonResponse({"error": str(e)}, status=400)

def payment_success(request):
    session_id  = request.GET.get("session_id")
    order_id = request.GET.get("order_id")

    if not session_id or not order_id:
        return JsonResponse({'error':'invalid session'}, status=400)

    try:
        session  = stripe.checkout.Session.retrieve(session_id)
        order = get_object_or_404(Order, order_id=order_id)

        customer_email = session.customer_email or session.customer_details.get("email", "")
        customer_name  = session.customer_details.name

        if session.payment_status == "paid":
            order = get_object_or_404(Order, order_id=order_id)
            payement_completed.delay(order.id)

            if 'coupon_id' in request.session:
                del request.session['coupon_id']
                request.session.modified = True

            return render(request, 'orders/payment_success.html', {'order':order})
        
        
        return JsonResponse({"error":"Payment not completed"}, status=400)
    
    except stripe.error.StripeError as e:
        return JsonResponse({"error":str(e)}, status=400)


def payment_failed(request):
    error_message = request.GET.get("error", "Your payment could not be processed. Please try again")
    return render(request, "orders/payment_failed.html", {'error_message':error_message})

@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    endpoint_secret = settings.STRIPE_WEBHOOK_KEY

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        return JsonResponse({"error": "Invalid payload"}, status=400)
    except stripe.error.SignatureVerificationError as e:
        return JsonResponse({"error": "Invalid signature"}, status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        order_id = session['metadata']['order_id']
        order = Order.objects.get(order_id=order_id)
        order.paid = True
        order.save()

        for item in order.items.select_related('product'):
            variation = item.product
            if variation.quantity >= item.quantity:
                variation.quantity -= item.quantity
                variation.save()
        

        coupon_id = session.get("metadata", {}).get("coupon_id")  

        if coupon_id:
            coupon = Coupon.objects.get(id=coupon_id)
            coupon.used = True
            coupon.save()

    return JsonResponse({"status": "success"}, status=200)


@login_required
def orders_history(request):
    orders = Order.objects.filter(email= request.user.email)
    return render(request, 'orders/orders_history.html', {'orders': orders})

@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, order_id=order_id)
    return render(request, 'orders/order_detail.html', {'order': order})

templates/orders/order_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');
        :root{
            --white-color:#fff;
            --black-color: #000;
            --light-white-color:#f0f0f0;
            --light-grey-color: #e5e5e5;
            --border-color: #d4d4d4;
            --primary-color:#3b82f6;
            --secondary-color:#404040;
            --overlay-dark-color: rgba(0, 0, 0, 0.6);
        }
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }
        body{
            background-color: white;
            font-family: 'Poppins', sans-serif;
            overflow-x: hidden;
        }
        .order_details .right_content{
            width: 400px;
            position: fixed;
            right:0;
            top: 0;
            bottom: 0;
            background-color: #F6F6F6;
            overflow-y: auto;
            scrollbar-color: #f1f1f1 transparent;
            overflow-y: auto; 
        }
        .right_content .header{
            padding: 30px 16px 22px;
            display: flex;
            align-items: center;
            border-bottom: 1px solid rgba(0, 0, 0, 0.253);   
        }
        .right_content .header h2{
            font-size: 19px;
            font-weight: 400;
            letter-spacing: 1px;
            margin-right: 10px;
        }
        .right_content .header svg{
            height: 30px;
            width: 30px;
            display: none;  
        }
        .right_content .product{
            display: flex;
            gap: 20px;
            padding: 30px 16px 22px;
        }
        .right_content .product img{
            height: 85px;
            width: 85px; 
        }
        .right_content .product p.name{
            font-size: 16px;
            text-transform: uppercase;
            color: black;
            font-weight: 500;
            letter-spacing: 1px;
            margin-bottom: 8px;
        }
        .right_content .product p.price{
            font-size: 18px;
            text-transform: uppercase;
            color: black;
            margin-bottom: 4px;
        }
        .right_content .product p.quantity{
            font-size: 14px;
        }
        /*scrollBar css*/
        .order_details .right_content::-webkit-scrollbar {
            width: 6px;
        }

        .order_details .right_content::-webkit-scrollbar-track {
            background: transparent;
        }

        .order_details .right_content::-webkit-scrollbar-thumb {
            background-color: #ccc;
            border-radius: 8px;
            transition: background-color 0.3s ease;
        }

        .order_details .right_content:hover::-webkit-scrollbar-thumb {
            background-color: #333;
        }
        /*scrollBar css*/
        .order_details .left_content{
            width: calc(100vw - 400px);
        }
        .order_details .left_content .header{
            margin: 80px 60px;
            position: relative; 
        }
        .left_content .header .title{
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .left_content .header .title a{
            font-size: 24px;   
            text-decoration: none;
            color: black;
            font-weight: 800;
            letter-spacing: 2px;   
        }
        .left_content .header svg{
            position: absolute;
            left: 0;
            top: 50%; 
            transform: translateY(-50%);
            height: 28px;   
            width: 28px; 
            transition: all ease .3s;  
        }
        .left_content .header svg:hover path{
            stroke: black;
            color: black;
        }
        .left_content .commande {
            width: 80%;
            margin: auto;
        }
        .left_content .commande h2{
            font-size: 18px;
            font-weight: 600;
            padding-bottom: 30px;
        } 
        .left_content .commande h2 span{
            font-weight: normal;
            letter-spacing: 2px;
        }
        .left_content .commande .info{
            padding: 20px 0;
            border-top: 1px solid rgba(0, 0, 0, 0.205);
        }
        .left_content .commande .info h2{
            font-size: 16px;
            font-weight: 500;
            padding-bottom: 10px;
        }
        .commande .info .sous_info{
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 16px; 
            font-weight: 400;
            color: #000000bb; 
            letter-spacing: .2px;
            flex-basis: 50%;
            text-transform: capitalize;
            margin-bottom: 6px;
        }
        .commande .info .coordonnees{
            display: grid;
            grid-template-columns: repeat(3, 1fr);

        }
        .commande .info .coordonnees .info{
            border: none;
            border-bottom: 1px solid rgba(0, 0, 0, 0.205);
        }
        @media screen and (max-width:768px){
            .order_details .right_content{
                width: 80%;
                height: 75px;
                margin:  20px auto 40px;
                position: relative;
                border-radius: 20px;
                box-shadow: 0px 4px 8px 0px rgba(255,100,124,0.07843),0px 4px 8px 0px rgb(238, 237, 237);
                background-color: #f0eeee;
                transition: all 1s ease;
            }
            .order_details .right_content.active{
                height: max-content;
            }
            .right_content .header{
                padding: 22px 16px 22px;
                border-bottom: 1px solid transparent;
                justify-content: center;
                cursor: pointer;
            }
            .right_content .header h2{ 
                text-align: center; 
            }
            .right_content .header svg.active{
                display: block;  
            }
            .order_details .left_content{
                width: 90vw;
            }
            .order_details .left_content .header{
                margin: 40px 30px;
            }
            .commande .info .coordonnees{
                grid-template-columns: repeat(1, 1fr);

            }
            .left_content .commande h2{
                font-size: 16px;
                padding: 15px 0 10px;
            } 
            .left_content .commande .info{
                padding: 10px 0;
            }
            .left_content .commande .info h2{
                padding-bottom: 7px;
            }
            .commande .info .sous_info{
                margin-bottom: 3px;
            }
        }
    </style>
</head>
<body>

<div class="order_details">
    <div class="left_content">
        <div class="header">
            <div class="title">
                <a href="">SENUOY</a>
            </div>
            <a href="{%url 'orders:orders_history'%}">
                <svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>
            </a>
        </div>
        <div class="commande">
            <h2>Commande <span>{{order.order_id}}</span></h2>
            <div class="info">
                <h2>Resume</h2>
                <div class="sous_info">
                    <div class="name">email</div>
                    <div class="value">{{order.email}}</div>
                </div>
                <div class="sous_info">
                    <div class="name">{{order.get_quantity}}  {%if order.get_quantity > 1%} articles {%else%} article{%endif%}</div>
                    <div class="value">$ {{order.get_total_cost}}</div>
                </div>
                <div class="sous_info">
                    <div class="name">created at</div>
                    <div class="value">{{order.created_at}}</div>
                </div>
            </div>
            <div class="info">
                <div class="coordonnees">
                    <div class="info">
                        <h2>Ville</h2> 
                        <div class="sous_info">
                            <div class="value">{{order.city}}</div>
                        </div>
                    </div>
                    <div class="info">
                        <h2>Code postal</h2> 
                        <div class="sous_info">
                            <div class="value">{{order.postal_code}}</div>
                        </div>
                    </div>
                    <div class="info">
                        <h2>adress</h2>
                        <div class="sous_info">
                            <div class="value">{{order.address}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="right_content">
        <div class="header">
            {%if order.get_quantity > 1%}
            <h2>{{order.get_quantity}} articles achetes</h2>
            {%else%}
            <h2>{{order.get_quantity}} article achete</h2>
            {%endif%}
            <svg class="down_arrow active" xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 24 24" id="arrow-down">
                <path fill="#565656" d="M17.71,11.29a1,1,0,0,0-1.42,0L13,14.59V7a1,1,0,0,0-2,0v7.59l-3.29-3.3a1,1,0,0,0-1.42,1.42l5,5a1,1,0,0,0,.33.21.94.94,0,0,0,.76,0,1,1,0,0,0,.33-.21l5-5A1,1,0,0,0,17.71,11.29Z"></path>
            </svg>
            <svg class="up_arrow" xmlns="http://www.w3.org/2000/svg" data-name="Layer 1" viewBox="0 0 24 24" id="arrow-up">
                <path fill="#565656" d="M17.71,11.29l-5-5a1,1,0,0,0-.33-.21,1,1,0,0,0-.76,0,1,1,0,0,0-.33.21l-5,5a1,1,0,0,0,1.42,1.42L11,9.41V17a1,1,0,0,0,2,0V9.41l3.29,3.3a1,1,0,0,0,1.42,0A1,1,0,0,0,17.71,11.29Z"></path>
            </svg>
        </div>
        <div class="products">
            {%for item in order.items.all%}
            <div class="product">
                <a href="{%url 'store:product_detail' item.product.id %}">
                    <img src="{{item.product.variation_images.first.image.image.url}}" alt="{{item.product.variation_images.first.image.alt}}">
                </a>
                <div class="info_product">
                    <p class="name">{{item.product.product.name}}</p>
                    <p class="price">${{item.get_cost}}</p>
                    <p class="quantity">{{item.quantity}} unite</p>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</div>

<script src="app.js" ></script>
<script>
    const order_right  = document.querySelector(".order_details .right_content")
    const order_header = document.querySelector('.right_content .header')
    const down_arrow   = document.querySelector('.order_details .right_content svg.down_arrow')
    const up_arrow     = document.querySelector('.order_details .right_content svg.up_arrow')
    order_header.addEventListener('click',()=>{
        order_right.classList.toggle('active')
        down_arrow.classList.toggle('active')
        up_arrow.classList.toggle('active')
    })
</script>

</body>
</html>

templates/orders/orders_history.html
{%extends 'base.html'%}
{%load static%}
{%block title%}Order Historique{%endblock%}
{%block content%}

<style>
    
    /****Order****/
        .orders_table .header{
            margin-top: 100px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
            position: relative;
        }
        .orders_table .header h1{
            text-align: center;
            color: black;
            margin-right: 10px;
            position: relative;
            font-size: clamp(12px, 4vw, 25px); 
        }
        .orders_table .header svg{
            width: clamp(12px, 4vw, 30px);
            height: clamp(12px, 4vw, 30px);
        }
        .orders_table .orders_list{
            margin-top: 20px;
        }
        .orders_list .order{
            width: 70%;
            display: flex;
            justify-content: space-around;
            align-items: center;
            background-color: white;
            margin: 0 auto 20px;
            padding: 25px 20px;
            border-radius: 20px;
            box-shadow: 0px 4px 8px 0px rgba(255,100,124,0.07843),0px 4px 8px 0px rgba(140,140,140,0.07843);
            
        }
        .orders_list .order p{
            font-weight: 400;
            font-size:17px;
            font-family: Arial, Helvetica, sans-serif;
            margin-bottom: 5px;
            color: #000000d7;
        }
        .orders_list .order p span{
            color: #000000d7;
            font-weight: 700; 
            text-transform: capitalize;
        }
        .orders_list .order .voir_detail{
            background-color: black;
            border: 1px solid transparent;
            color: white;
            padding:  8px 10px; 
            border-radius: 7.5px;
            cursor: pointer;
            font-size: 13px;
            text-transform: uppercase;
            transition: all .3s ease;  
        }
        .orders_list .order .voir_detail:hover{
            background-color: white;
            color: black;
            border: 1px solid black;
        }
        .orders_list .order p.status{
            font-size: 30px;
        }
        .orders_list .order i{
            font-size: 30px;
            position: relative;
            top: 4px;
            font-weight: 900;  
        }
        .orders_table .orders_list .back_to_home{
            width: 70%;
            margin: auto;
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .back_to_home a{
            color: #4B5563; 
            text-decoration: none;
            transition: all .3s ease;
            border-bottom: 1px solid transparent;
        }
        .back_to_home a:hover{
            border-bottom: 1px solid black;
            color: black;
        }

        .orders_list .order_vide{
            font-size: clamp(12px, 3.5vw, 32px);
            font-weight: 600;
            letter-spacing: -.003em;
            color: #6e6e73;
            text-align: center;
            padding: 40px 0;
        }
        @media screen and (max-width:768px){
            .orders_list .order{
                width: calc(100% - 20px);
                display: flex;
                justify-content: space-between;
                margin: 12px auto;
            }
            .orders_list .order p{
                font-size:14px;
            }
            .orders_table .orders_list .back_to_home{
                width: 100%;
                padding-left: 10px;
            }
        }
    /****Order****/
</style>

<!--Orders-->
<section class="orders_table">
    <div class="header">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="shopping-cart-alt"><path fill="#4F9649" d="M21.5,15a3,3,0,0,0-1.9-2.78l1.87-7a1,1,0,0,0-.18-.87A1,1,0,0,0,20.5,4H6.8L6.47,2.74A1,1,0,0,0,5.5,2h-2V4H4.73l2.48,9.26a1,1,0,0,0,1,.74H18.5a1,1,0,0,1,0,2H5.5a1,1,0,0,0,0,2H6.68a3,3,0,1,0,5.64,0h2.36a3,3,0,1,0,5.82,1,2.94,2.94,0,0,0-.4-1.47A3,3,0,0,0,21.5,15Zm-3.91-3H9L7.34,6H19.2ZM9.5,20a1,1,0,1,1,1-1A1,1,0,0,1,9.5,20Zm8,0a1,1,0,1,1,1-1A1,1,0,0,1,17.5,20Z"></path></svg>
        <h1>Orders</h1>
    </div>
    <div class="orders_list">
        {%if orders%}
            <p class="back_to_home">
                <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>    
                <a href="{%url 'store:home'%}">Back to Home</a>
            </p>
            {%for order in orders%}
            <div class="order">
                <div class="commande">
                    <p class="order_id"><span>Commande: </span>{{order.order_id}}</p>
                    <p class="created_at">{{order.created_at}}</p>
                </div>
                <p class="qts:"><span>Quantity:</span>{{order.get_quantity}}</p>
                <p class="price">${{order.get_total_cost}}</p>
                <p class="staus">
                    {%if order.paid%}
                        <i class="uil uil-check"></i>
                    {%else%}
                        <i class="uil uil-multiply"></i>
                    {%endif%}
                    Paid
                </p>
                <a href="{%url 'orders:order_detail' order.order_id %}" class="voir_detail" style="text-decoration: none;">voir detail</a>
            </div>
            {%endfor%}
        {%else%}
            <p class="order_vide" style="text-align: center;">Vous n'avez pas encore passé de commande. <a href="{% url 'store:list_product' %}">Commander maintenant</a>.</p>
        {%endif%}
    </div>
</section>
<!--Orders-->

{%endblock%}

templates/orders/payment_success.html
{%extends 'base.html'%}
{%load static%}

{%block title%}Payment successfull{%endblock%}

{%block content%}
<div class="alert">
    <div class="alert_access">
        <h4 class="alert_heading">Paymenet successfull.</h4>
        <p>Order <b>{{order.order_id}}</b> has been paid successfully.</p>
    </div>
</div>
{%endblock%}