loyalty/urls.py
from django.urls import path
from . import views

app_name = 'loyalty'

urlpatterns = [
    path('home/', views.home_loyalty, name='home_loyalty'),
    path('rewards/list/', views.rewards_list, name='rewards_list'),
    path('reward_details/<int:reward_id>/', views.reward_details, name='reward_details'),
    path('get_reward/<int:reward_id>/', views.get_reward, name='get_reward'),
    path('rewards/gained/', views.rewards_gained, name='rewards_gained'), 
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import redirect
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('newsletter/', include('newsletter.urls', namespace='newlsetter')),
    path('loyalty/', include('loyalty.urls', namespace='loyalty')),
    path('tombola/', include('tombola.urls', namespace='tombola')),
    
    #apis
    path('v1/api/', include('apis.urls', namespace='apis')),

    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),



    
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('list_product/', views.list_product, name='list_product'),
    path('product/<variation_id>/', views.product_detail, name='product_detail'),
    path('category/<category_slug>/', views.product_by_category, name='product_by_category'),
]

loyalty/models.py
from django.db import models
from accounts.models import Account

class LoyaltyPoint(models.Model):
    user       = models.OneToOneField(Account, on_delete=models.CASCADE) 
    points     = models.IntegerField(default=0)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} — {self.points} pts"
    

    def add_points(self, amount):
        self.points += amount
        self.save()

    def redeem_points(self, amount):
        if self.points  >= amount:
            self.points -= amount
            self.save()


class Reward(models.Model):
    REWARD_TYPES = [
        ('cinema', 'Cinema Ticket'),
        ('discount', 'Percentage Discount'),
    ]
    title                = models.CharField(max_length=100)
    description          = models.TextField(blank=True)
    owner                = models.CharField(max_length=100, default="senuoy")
    image                = models.ImageField(upload_to='loyality/')
    points_required      = models.IntegerField()
    reward_type          = models.CharField(max_length=20, choices=REWARD_TYPES)
    discount_percent     = models.IntegerField(null=True, blank=True)
    cinema_ticket_code   = models.CharField(max_length=100, blank=True, null=True, unique=True)
    conditions_generales = models.CharField(max_length=255, blank=True, null=True)
 
    def __str__(self):
        return self.title



class RedeemedReward(models.Model):
    user        = models.ForeignKey(Account, on_delete=models.CASCADE)
    reward      = models.ForeignKey(Reward, on_delete=models.CASCADE)
    redeemed_at = models.DateTimeField(auto_now_add=True)
    used        = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} redeemed {self.reward.title}"

loyalty/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import LoyaltyPoint, Reward, RedeemedReward
from django.contrib.auth.decorators import login_required

import string, random
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from datetime import timedelta
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
import weasyprint
from io import BytesIO

from .models import Reward, LoyaltyPoint, RedeemedReward
from coupons.models import Coupon 

@login_required
def home_loyalty(request):
    user    = request.user
    points  = get_object_or_404(LoyaltyPoint, user=user)
    context = {
        'user':user,
        'points':points,
    }
    return render(request, 'loyalty/home_loyalty.html', context)

@login_required
def rewards_list(request):
    rewards = Reward.objects.all()
    loyalty = LoyaltyPoint.objects.filter(user=request.user).first()
    points = loyalty.points if loyalty else 0
    context = {
        'rewards': rewards,
        'points': points,
    }
    return render(request, 'loyalty/rewards_list.html', context)

@login_required
def reward_details(request, reward_id):
    reward = get_object_or_404(Reward, pk=reward_id)
    loyalty = LoyaltyPoint.objects.filter(user=request.user).first()
    points = loyalty.points if loyalty else 0
    context = {
        'reward': reward,
        'points': points,
    }
    return render(request, 'loyalty/reward_details.html', context)


def generate_coupon_code(length=8):
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=length))

@login_required
def get_reward(request, reward_id):
    reward  = get_object_or_404(Reward, id=reward_id)
    loyalty, created = LoyaltyPoint.objects.get_or_create(user=request.user)

    if loyalty.points < reward.points_required:
        messages.error(request, "Vous n'avez pas assez de points.")
        return redirect('loyalty:rewards_list')


    # Deduct points
    loyalty.redeem_points(reward.points_required)

    # Save redemption
    RedeemedReward.objects.create(
        user=request.user,
        reward=reward,
        redeemed_at=timezone.now(),
        used=False
    )

    subject = "Votre récompense chez Senuoy"
    message = ""
    
    if reward.reward_type == "discount":
        # Create coupon valid for 1 year
        now = timezone.now()
        code = generate_coupon_code()
        coupon = Coupon.objects.create(
            code=code,
            valid_from=now,
            valid_to=now + timedelta(days=365),
            discount=reward.discount_percent ,
            active=True
        )

        message = (
            f"Félicitations ! Vous avez débloqué une réduction de {coupon.discount}%.\n\n"
            f"Code: {coupon.code}\n"
            f"Valable en ligne jusqu'au {coupon.valid_to.strftime('%d/%m/%Y')}.\n"
        )
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [request.user.email],
            fail_silently=False,
        )

    elif reward.reward_type == "cinema":
        code = reward.cinema_ticket_code or "CODE-INDISPONIBLE"
        message = (
            f"Félicitations ! Vous avez débloqué un ticket de cinéma.\n\n"
        )
        context = {
            'code':code,
            'full_name':request.user.get_full_name,
        }
        html = render_to_string('loyalty/ticket_pdf.html', context)
        out = BytesIO()
        weasyprint.HTML(string=html).write_pdf(out)

        email = EmailMessage(
        subject=subject,
        body = message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=[request.user.email]
        )
        email.attach(f'ticket_{code}.pdf', out.getvalue(), 'application/pdf')
        email.send()
        

    else:
        message = "Récompense débloquée, mais aucun type reconnu."
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [request.user.email],
            fail_silently=False,
        )

    context = {
        "message": "Récompense débloquée et envoyée par email !",
    }
    return render(request, 'loyalty/reward_done.html', context)



def rewards_gained(request):
    rewards = RedeemedReward.objects.filter(user=request.user)
    return render(request, 'loyalty/rewards_gained.html', {'rewards':rewards})

templates/loyalty/reward_details.html
{%extends 'base.html'%}

{%load static%}
{% load loyalty_extras %}

{%block title%}Reward details{%endblock%}

{%block content%}
<style>
    
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');

    :root{
        --white-color:#fff;
        --black-color: #000;
        --light-white-color:#f0f0f0;
        --light-grey-color: #e5e5e5;
        --border-color: #d4d4d4;
        --primary-color:#3b82f6;
        --secondary-color:#404040;
        --overlay-dark-color: rgba(0, 0, 0, 0.6);
    }
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }
    body{
        background-color: #F4F4F4;
        font-family: 'Poppins', sans-serif;
        overflow-x: hidden;
    }
    /******loyality*****/
    .loyality{
        width: 70%;
        margin: 0 auto;
        margin-top: 120px;
    }
    .loyality .header p{
        display: flex;
        gap: 5px;
        align-items: center;
        margin-bottom: 0px; 
        margin-top: 20px;
        padding-left: 10px;
        max-width: max-content;
    }
    .loyality .header p a{
        color: #4B5563; 
        text-decoration: none;
        transition: all .3s ease;
        border-bottom: 1px solid transparent;
    }
    .loyality .header p:hover a,
    .loyality .header p:hover svg path{
        border-bottom: 1px solid black;
        color: black;
        stroke: black;
    }
    .loyalty_awards h1{
        white-space: pre;
        font-size: clamp(16px, 4vw, 30px);
        font-weight: 600;
        letter-spacing: -.003em;
        line-height: 1.0834933333;
        color: #6e6e73;
        display: block;
        margin: 0 0 20px; 
        text-align: center;
    }
    .loyalty_awards .awards{
        display: grid;
        grid-template-columns: 1fr;
        margin-bottom: 30px;
    }
    .loyalty_awards .awards .award{
        background-color: white;
        border: 1px solid rgba(0, 0, 0, 0.13);
        border-radius: 20px;
        padding: 20px 30px;
        text-decoration: none;
        color: black;
        transition: all .3s ease;
    }
    .award .info_award{
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 0px; 
    }
    .award .info_award img{
        width: 95%; 
        height: 400px;
        border-radius: 20px;     
    }
    .award .info_award .details{
        padding: 15px 0; 
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }
    .info_award .details .title{
        font-size: 13px;
        color: #3b82f6;
        font-weight: 500; 
        margin: 20px 0 5px;
    }
    .info_award .details .description{
        color: #000;
        font-weight: 700;
        letter-spacing: .2px;
    }
    .info_award .details .points_required{
        border: 1px solid #5b81be2d;
        max-width: max-content;
        padding: 2px 10px;
        background-color: #5b81be2d;
    }
    .award.award.debloquer .info_award .details .points_required{
        background-color: #5bbe6c2d;
    }
    .info_award .details .conditions p.title{
        font-weight: 700; 
        font-size: 21px;
        color: black;
        margin: 5px 0;
        letter-spacing: 1px; 
    }
    .info_award .details .conditions p.text{
        font-size: 15px;
        font-weight: 400;
        line-height: 21px;
        color: #0a0a0a;  
    }
    .loyalty_awards .award .progress_award{
        padding-top: 10px;
        margin-top: 20px;
        border-top: 1px solid rgba(0, 0, 0, 0.253);
    }
    .award .progress_award .progress_info{
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .award .progress_award .progress_info p{
        font-size: 14px;
        font-weight: 400; 
        letter-spacing: .2px;
    }
    .award .progress_award .progress_bar_bg{
        margin-top: 5px;
        width: 100%;
        height: 8px; 
        border-radius: 8px;
        background-color: #00000010;
        position: relative;
    }
    .award .progress_award .progress_bar{
        position: absolute;
        left: 0;
        height: 100%;
        width: 81%;
        background-color: #9333EA;
    }
    .award .progress_award .btn_bloc{
        width: 100%;
        margin-top: 20px; 
        background-color: #9333EA;
        color: #fff;
        border-radius: 10px;
        border: 1px solid #9333EA;
        cursor: pointer;
        margin-bottom: 13px;
        letter-spacing: 1px;
        text-transform: capitalize; 
        transition: all .3s ease;
        position: relative;
        height: 42px;
    }
    .award .progress_award .btn_bloc a{
        color: white;
        text-decoration: none;
        transition: all .3s ease;
        position: absolute;
        top: 0; bottom: 0; right: 0; left: 0;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .award .progress_award .btn_bloc:hover a{
        color: #9333EA;
    }
    .award .progress_award .btn_bloc:hover{
        background-color: #fff;
        color: #9333EA;
        border: 1px solid #9333EA;
    }
    .award .progress_award .btn_bloc.deactive,
    .award .progress_award .btn_bloc.deactive:hover{
        background-color: #9233ea98;
        color: white;
        border: 1px solid #9233ea98;
        text-decoration: none;
    }
    .award .progress_award .btn_bloc.deactive a,
    .award .progress_award .btn_bloc.deactive:hover a{
        color: white;
        text-decoration: none;
    }
    /******loyality*****/
    @media only screen and (max-width: 1200px) {
        .loyality{
            width: 80%;
        }
    }
    @media only screen and (max-width: 768px) {
        .loyality{
            width: 90%;
        }
        .loyality_header{
            display: flex;
            flex-direction: column;
            gap: 20px;
            padding: 20px 0px;
        } 
        .award .info_award{
            grid-template-columns: 1fr;
        }
    }
</style>

<div class="loyality">
    <div class="header">
        <p>
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>    
            <a href="{% url 'loyalty:home_loyalty' %}">Back</a>
        </p>
    </div>
    <div class="loyalty_awards">
        <h1>Recomponse a debloquer</h1>
        <div class="awards">
            {% with diff=reward.points_required|subtract:points %}
            <div href="#" class="award {% if diff < 0 %}debloquer{% endif %}">
                <div class="info_award">
                    <img src="{{reward.image.url}}" alt="">
                    <div class="details">
                        <div class="title_description">
                            <div class="title">{{reward.owner}}</div>
                            <div class="description">{{reward.title}}</div>
                        </div>
                        <div class="conditions">
                            <div class="condition">
                                <p class="title">Description</p>
                                <p class="text">{{reward.description}}</p>
                            </div>
                            <div class="condition">
                                <p class="title">Conditions generales</p>
                                <p class="text">{{reward.conditions_generales}}</p>
                            </div>
                        </div>
                        <div class="points_required">
                            {% if diff < 0 %}
                                <i class="uil uil-key-skeleton-alt"></i>
                            {% else %}
                                <i class="uil uil-lock"></i>
                            {% endif %}
                            {{ reward.points_required }} pts
                        </div>
                    </div>
                </div>
                <div class="progress_award">
                    {% if diff > 0 %}
                        <div class="progress_info">
                            <p>Il vous faut encore {{ diff }} pts pour gagner</p>
                            <p class="progress_percent">{{ points|progress:reward.points_required }}%</p>
                        </div>
                        <div class="progress_bar_bg">
                            <div class="progress_bar"></div>
                        </div>
                        <button class="btn_bloc deactive">
                            <a>Debloquer cette Recomponse</a>
                        </button>
                    {% else %}
                        <div class="progress_info">
                            <p>Pret(e) ? Debloquer la recompense</p>
                            <p class="progress_percent">{{ points|progress:reward.points_required }}%</p>
                        </div>
                        <div class="progress_bar_bg">
                            <div class="progress_bar"></div>
                        </div>
                        <button class="btn_bloc">
                            <a href="{%url 'loyalty:get_reward' reward.id%}">Debloquer cette Recomponse</a>
                        </button>
                    {% endif %}
                </div>
            </div>
            {%endwith%}
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const awards_progress = document.querySelectorAll(".loyalty_awards .award .progress_award");
        awards_progress.forEach((award) => {
            const progressPercentEl = award.querySelector('.progress_info .progress_percent');
            const progressBar = award.querySelector('.progress_bar_bg .progress_bar');

            if (progressPercentEl && progressBar) {
                const progress_percent = progressPercentEl.textContent.trim();
                progressBar.style.width = progress_percent;
            }
        });
    });
</script>


{%endblock%}

templates/loyalty/reward_done.html
{%extends 'base.html' %}
{%load static%}
{%block title%}reward sends{%endblock%}
{%block content%}
<style>
    .back_to_home{
        width: 80%;
        margin: auto;
        margin-bottom: 20px;
        display: flex;
        align-items: center;
        gap: 10px;
    }
    .back_to_home a{
        color: #4B5563; 
        text-decoration: none;
        transition: all .3s ease;
        border-bottom: 1px solid transparent;
    }
    .back_to_home a:hover{
        border-bottom: 1px solid black;
        color: black;
    }
</style>

<div style="margin-top: 120px;">
    <p class="back_to_home">   
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>    
        <a href="{%url 'store:home'%}">Back to Home</a>
    </p>

    <div class="alert" style="margin-top: 0;">
        <div class="alert_access">
            <h4 class="alert_heading">Well Done.</h4>
            <p>{{message}}</p>
        </div>
    </div>
</div>
{%endblock%}

templates/loyalty/rewards_list.html
{%extends 'base.html'%}

{%load static%}
{% load loyalty_extras %}

{%block title%}List Rewards{%endblock%}

{%block content%}
<style>
    
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');

    :root{
        --white-color:#fff;
        --black-color: #000;
        --light-white-color:#f0f0f0;
        --light-grey-color: #e5e5e5;
        --border-color: #d4d4d4;
        --primary-color:#3b82f6;
        --secondary-color:#404040;
        --overlay-dark-color: rgba(0, 0, 0, 0.6);
    }
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }
    body{
        background-color: #F4F4F4;
        font-family: 'Poppins', sans-serif;
        overflow-x: hidden;
    }

    /******loyality*****/
    .loyality{
        width: 70%;
        margin: 0 auto;
        margin-top: 120px;
    }
    .loyality_header{
        background-color: white;
        border-radius: 30px;
        display: flex;
        align-items: center;
        gap: 100px;
        padding: 20px 40px;
        border: 1px solid  rgba(140,140,140,0.07843);
        box-shadow: 0px 4px 8px 0px rgba(100, 219, 255, 0.078),0px 4px 8px 0px rgba(140,140,140,0.07843);
    }
    .loyality_header .user_info{
        display: flex;
        align-items: center;
    }
    .loyality_header .user_info img{
        width: 150px;
        height: 150px;
        background-color: #0082c31e;
        border-radius: 50%;
        margin-right: 30px;
    }
    .loyality_header .user_info .info_persona p{
        font-size: 17px;
        letter-spacing: .5px;
        margin-bottom: 3px;
        font-weight: 600;
        color: rgba(0, 0, 0, 0.699);

    }
    .user_info .info_persona p.name{
        color: black;
        text-transform: uppercase;
        margin-bottom: 4px;
    }
    .loyality_header .points{
        display: flex;
        gap: 20px; 
    }
    .loyality_header .points .title{
        font-weight: 800;
        font-size: 19px; 
        color: #000000c7; 
        letter-spacing: .6px;
    }
    .loyality_header .points .value{
        border: 1px solid #0082C3;
        padding: 5px  12px;
        border-radius: 12px;
        background-color: #0082C3;
        color: white;
        letter-spacing: 1px;
        font-weight: 700;
    }
    .loyality .header p{
        display: flex;
        gap: 5px;
        align-items: center;
        margin-bottom: 10px; 
        padding-left: 10px;
        max-width: max-content;
    }
    .loyality .header p a{
        color: #4B5563; 
        text-decoration: none;
        transition: all .3s ease;
        border-bottom: 1px solid transparent;
    }
    .loyality .header p:hover a,
    .loyality .header p:hover svg path{
        border-bottom: 1px solid black;
        color: black;
        stroke: black;
    }
    .loyalty_awards h1{
        white-space: pre;
        font-size: clamp(16px, 4vw, 30px);
        font-weight: 600;
        letter-spacing: -.003em;
        line-height: 1.0834933333;
        color: #6e6e73;
        display: block;
        margin: 40px 0 20px; 
        text-align: center;
    }
    .loyalty_awards .awards{
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 30px;
    }
    .loyalty_awards .awards .award{
        background-color: white;
        border: 1px solid rgba(0, 0, 0, 0.13);
        border-radius: 20px;
        padding: 20px 30px;
        text-decoration: none;
        color: black;
        transition: all .3s ease;
    }
    .loyalty_awards .awards .award:hover{
        box-shadow: 0px 4px 8px 0px rgba(48, 52, 53, 0.205),0px 4px 8px 0px rgba(140,140,140,0.07843);
    }
    .award .info_award{
        display: flex;
        gap: 10px; 
    }
    .award .info_award img{
        height: 150px; 
        width: 150px; 
    }
    .award .info_award .details{
        padding: 15px 0; 
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }
    .info_award .details .title{
        font-size: 13px;
        color: #3b82f6;
        font-weight: 500; 
    }
    .info_award .details .description{
        color: #000;
        font-weight: 700;
        letter-spacing: .2px;
    }
    .info_award .details .points_required{
        border: 1px solid #5b81be2d;
        max-width: max-content;
        padding: 2px 10px;
        background-color: #5b81be2d;
    }
    .award.award.debloquer .info_award .details .points_required{
        background-color: rgba(144, 228, 144, 0.733);
    }
    .loyalty_awards .award .progress_award{
        padding-top: 10px;
        margin-top: 20px;
        border-top: 1px solid rgba(0, 0, 0, 0.253);
    }
    .award .progress_award .progress_info{
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .award.debloquer .progress_award .progress_info{
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 10px;
        margin: 20px 0;
    }
    .award.debloquer .progress_award .progress_info i{
        color: #0082C3; 
        font-size:21px;
    }
    .award.debloquer .progress_award .progress_info p{
        font-size:19px; 
        margin: 0; 
        padding:0;
    }
    .award .progress_award .progress_info p{
        font-size: 14px;
        font-weight: 400; 
        letter-spacing: .2px;
    }
    .award .progress_award .progress_bar_bg{
        margin-top: 5px;
        width: 100%;
        height: 8px; 
        border-radius: 8px;
        background-color: #00000010;
        position: relative;
        overflow: hidden;
    }
    .award .progress_award .progress_bar{
        position: absolute;
        left: 0;
        height: 100%;
        width: 81%;
        background-color: #0082C3;
    }
    /******loyality*****/
    @media only screen and (max-width: 1200px) {
        .loyality{
            width: 80%;
        }
        .loyality .loyality_header{
            gap: 100px; 
            padding: 20px 20px;
        }
    }
    @media only screen and (max-width: 900px) {
        .loyality{
            width: 80%;
        }
        .loyality .loyality_header{
            gap: 10px;  
            padding: 20px 10px;
        }
    }
    @media only screen and (max-width: 768px) {
        .loyality{
            width: 90%;
        }
        .loyality_header{
            display: flex;
            flex-direction: column;
            gap: 20px;
            padding: 20px 0px;
        }  
        .loyality_header .user_info{
            display: flex;
            align-items: center;
        }
        .loyality_header .user_info img{
            width: 120px;
            height: 120px;
            margin-right: 10px;
        }
        .loyality_header .user_info .info_persona p{
            font-size: 15px;

        }
        .loyality_header .points{
            align-items: center;
            gap: 10px; 
        }
        .loyality_header .points .title{
            font-size: 17px; 
        }
        .loyality_header .points .value{
            font-size: 14px; 
        } 
        .loyalty_awards .awards{
            grid-template-columns: 1fr;
        }
    }
    
</style>

<div class="loyality">
    <div class="header">
        <p>
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 15.8334L4.16667 10L10 4.16669" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M15.8333 10H4.16667" stroke="#4B5563" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>    
            <a href="{% url 'loyalty:home_loyalty' %}">Back</a>
        </p>
    </div>
    <div class="loyality_header">
        <div class="user_info">
            <img src="{%static 'images/Sample_User_Icon.png'%}" alt="">
            <div class="info_persona">
                <p class="name">{{request.user.get_full_name}}</p>
                <p class="email">{{request.user.email}}</p>
                <p class="phone">{{request.user.phone_number}}</p>
            </div>
        </div>
        <div class="points">
            <p class="title">Solde de points:</p>
            <p class="value">{{points}} pts</p>
        </div>
    </div>
    <div class="loyalty_awards">
        <h1>Recomponse</h1>
        <div class="awards">
        {% for reward in rewards %}
            {% with diff=reward.points_required|subtract:points %}
                <a href="{%url 'loyalty:reward_details' reward.pk%}" class="award {% if diff < 0 %}debloquer{% endif %}">
                    <div class="info_award">
                        <img src="{{ reward.image.url }}" alt="">
                        <div class="details">
                            <div class="title_description">
                                <div class="title">{{ reward.owner }}</div>
                                <div class="description">{{ reward.title }}</div>
                            </div>
                            <div class="points_required">
                                {% if diff < 0 %}
                                    <i class="uil uil-key-skeleton-alt"></i>
                                {% else %}
                                    <i class="uil uil-lock"></i>
                                {% endif %}
                                {{ reward.points_required }} pts
                            </div>
                        </div>
                    </div>
                    <div class="progress_award">
                        {% if diff > 0 %}
                            <div class="progress_info">
                                <p>Il vous faut encore {{ diff }} pts pour gagner</p>
                                <p class="progress_percent">{{ points|progress:reward.points_required }}%</p>
                            </div>
                            <div class="progress_bar_bg">
                                <div class="progress_bar"></div>
                            </div>
                        {% else %}
                            <div class="progress_info">
                                <i class="uil uil-check-circle"></i>
                                <p>Pret a etre debloquer</p>
                            </div>
                        {% endif %}
                    </div>
                </a>
            {% endwith %}
        {% endfor %}
</div>

    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const awards_progress = document.querySelectorAll(".loyalty_awards .award .progress_award");
        awards_progress.forEach((award) => {
            const progressPercentEl = award.querySelector('.progress_info .progress_percent');
            const progressBar = award.querySelector('.progress_bar_bg .progress_bar');

            if (progressPercentEl && progressBar) {
                const progress_percent = progressPercentEl.textContent.trim();
                progressBar.style.width = progress_percent;
            }
        });
    });
</script>


{%endblock%}